name: tyler

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  tyler:
    type: tool
    platform: macOS
    sources:
        - path: src/
        - path: deps/osdialog
          includes:
            - "osdialog.[ch]"
            - "osdialog_mac.m"
        - path: build/
          type: folder
        - path: deps/
          type: folder
        - path: assets/
          type: folder
        - path: README.md
        - path: project.yml
        - path: Makefile
    dependencies:
        - target: cimgui
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps,
                              $(PROJECT_DIR)/deps/imgui]
        OTHER_CFLAGS: [-x objective-c,
                       -fobjc-arc]
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps/]
        OTHER_CFLAGS: [-x objective-c,
                       -DSOKOL_METAL,
                       -fobjc-arc]
  cimgui:
    type: library.dynamic
    platform: macOS
    sources:
        - path: deps/
          includes:
            - "cimgui.*"
        - path: deps/imgui/
          includes:
            - "*.cpp"
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps/,
                              $(PROJECT_DIR)/deps/imgui]
  
