name: tyler

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  cimgui:
    type: library.dynamic
    platform: macOS
    sources:
        - path: deps/cimgui
          includes:
            - "cimgui.*"
        - path: deps/cimgui/imgui/
          includes:
            - "*.cpp"
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps/cimgui,
                              $(PROJECT_DIR)/deps/cimgui/imgui]
  tyler:
    type: tool
    platform: macOS
    sources:
        - path: src/
          excludes:
            - "test.c"
        - path: build/
          type: folder
        - path: deps/
          type: folder
        - path: assets/
          type: folder
        - path: README.md
        - path: project.yml
        - path: Makefile
    dependencies:
        - target: cimgui
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps,
                              $(PROJECT_DIR)/deps/sokol_helpers,
                              $(PROJECT_DIR)/src,
                              $(PROJECT_DIR)/deps/cimgui,
                              $(PROJECT_DIR)/deps/cimgui/imgui]
        OTHER_CFLAGS: [-x objective-c,
                       -DSOKOL_METAL,
                       -fobjc-arc]
  ty_example:
    type: tool
    platform: macOS
    source:
        - path: src/test.c
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps,
                              $(PROJECT_DIR)/deps/sokol_helpers]
        OTHER_CFLAGS: [-x objective-c,
                       -DSOKOL_METAL,
                       -fobjc-arc]
